#
# Development
#
SOURCE ?= src

.PHONY: $(SOURCE)
$(SOURCE):
	version="$$(dpkg-parsechangelog -S Version)" && \
	debian_version="$${version%%-*}" && \
	reversion="$${version##*-}" && \
	rockchip_version="$${version#$${debian_version}-}" && \
	rockchip_version="$${rockchip_version%-$${reversion}}" && \
	ln -sTf "$$rockchip_version" "$@"

.PHONY: pkg.conf
pkg.conf:
	version="$$(dpkg-parsechangelog -S Version)" && \
	debian_version="$${version%%-*}" && \
	reversion="$${version##*-}" && \
	rockchip_version="$${version#$${debian_version}-}" && \
	rockchip_version="$${rockchip_version%-$${reversion}}" && \
	cp "pkg.conf.$$rockchip_version" "$@"

SRC-MAN		:=	man
SRCS-MAN	:=	$(wildcard $(SRC-MAN)/*.md)
MANS		:=	$(SRCS-MAN:.md=)
.PHONY: build-man
build-man: $(MANS)

$(SRC-MAN)/%: $(SRC-MAN)/%.md
	pandoc "$<" -o "$@" --from markdown --to man -s

SRC-DEB		:=	$(SOURCE)
.PHONY: build-deb
build-deb: $(SRC-DEB)
# delete looping symbolic link, or find will return error
	rm -f "$^/ubuntu-build-service/bullseye-desktop-armhf/bullseye-desktop-armhf"
	find -L "$^" -name "camera_engine_rkaiq_*_arm64.deb" -exec fixup/fix_rkaiq {} +
	find -L "$^" -name "rktoolkit_*_arm64.deb" -exec fixup/fix_rktoolkit {} +
	find -L "$^" -name "chromium-x11_*_arm64.deb" -exec fixup/fix_chromium {} +
# libdrm contains duplicated packages as libdrm-debs
	if [ $(shell readlink "$^") == "linux-6.12-stan-rkr1" ]; then \
		rm -f "$^/packages/arm64/libdrm"; \
	fi

pre_build: build-deb build-man $(SOURCE) pkg.conf
