#!/usr/bin/env bash
#
# There are several incompatible camera_engine_rkaiq packages with the exact
# same package name and version, causing a big mess:
# * freight and aptly (the apt repo generator) will overwrite packages with same
#   name and version.
# * We have no way to pin specific product to the matching variant.
#
# As such, we add a unique suffix to version so they can coexist in our apt
# repo, and then we let them provide virtual package, so other package's
# dependencies do not have to pin to a specific version, and can be easily
# upgraded.
#
# Some issues preventing the service from running:
# * Script must be executable for the service to run.
# * systemd.wants expects symbolic link, and will ignore real file.
#

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
# shellcheck source=fixup/libfixup.sh
source "$SCRIPT_DIR/libfixup.sh"

fixup_callback() {
    local file_name soc package_name version
    file_name="$1"

    soc="$(sed -E "s/.*(rk[0-9]+).*/\1/" <<< "$file_name")"
    package_name="$(grep "Package:" control | cut -d' ' -f2)"
    sed -i -E "s/^(Version: .*)$/\1-$soc/" control
    version="$(grep "^Version:" control | cut -d ' ' -f2)"
    cat <<EOF >> control
Provides: $package_name-$soc (= $version)
Conflicts: $package_name-$soc (<< $version)
Replaces: $package_name-$soc (<< $version)
EOF

    extract data.tar etc/init.d/rkaiq_3A.sh
    chmod +x etc/init.d/rkaiq_3A.sh
    replace data.tar etc/init.d/rkaiq_3A.sh

    mkdir -p etc/systemd/system/sysinit.target.wants
    ln -s /lib/systemd/system/rkaiq_3A.service etc/systemd/system/sysinit.target.wants/rkaiq_3A.service
    replace data.tar etc/systemd/system/sysinit.target.wants/rkaiq_3A.service
}

fixup_loop "$@"
