#!/usr/bin/env bash
#
# Rockchip begins to include adbd in rktoolkit, which is newer than
# android-tools-adbd we got from Debian Buster.
#
# However, the Debian 11 SDK contains the same package with the same version,
# so using its own name as dependency can break adbd related functionality.
#
# Add a virtual package for dependency.
# This is fixed at least in RK3528's Debian 11 rkr6 SDK, which also contains adbd.
#

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
# shellcheck source=fixup/libfixup.sh
source "$SCRIPT_DIR/libfixup.sh"

fixup_callback() {
    echo "Provides: rockchip-adbd-provider" >> control
}

fixup_loop "$@"
