#!/usr/bin/env bash
#
# Rockchip Chromium depends on libmali.so.1, which is provided by libmali driver.
#
# Patching the binary to use libgbm1 instead.
#

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
source "$SCRIPT_DIR/libfixup.sh"

fixup_callback() {
    extract data.tar usr/lib/chromium/chromium-bin
    patchelf --replace-needed libmali.so.1 libgbm.so.1 usr/lib/chromium/chromium-bin
    replace data.tar usr/lib/chromium/chromium-bin
    rm -rf usr/
}

fixup_loop "$@"
