#!/usr/bin/env bash
#
# Rockchip Chromium depends on libmali.so.1, which is provided by libmali driver.
# Patching the binary to use libgbm1 instead, so it can use open source GPU driver.
#
# Also add the missing libc++1 dependency.
#

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
# shellcheck source=fixup/libfixup.sh
source "$SCRIPT_DIR/libfixup.sh"

fixup_callback() {
    if ! grep "^Depends:" control | grep "libc++1"
    then
        sed -Ei "s/^(Depends:)/\1 libc++1,/" control
    fi

    extract data.tar usr/lib/chromium/chromium-bin
    patchelf --replace-needed libmali.so.1 libgbm.so.1 usr/lib/chromium/chromium-bin
    patchelf --replace-needed libmali-hook.so.1 libgbm.so.1 usr/lib/chromium/chromium-bin
    replace data.tar usr/lib/chromium/chromium-bin
    rm -rf usr/
}

fixup_loop "$@"
